apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../postgres.yaml
  - ../../rabbitmq.yaml
  - ../../mongo.yaml
  - ../../mailpit.yaml
  - ../../pvc.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../pdb.yaml
  - ../../hpa.yaml

secretGenerator:
  - name: video-processor-secrets
    envs:
      - ../../env/local.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: video-processor-api
    newName: video-processor-api
    newTag: latest
