apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-processor-data
  namespace: video-processor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi