apiVersion: v1
kind: Secret
metadata:
  name: video-processor-secrets
  namespace: video-processor
type: Opaque
stringData:
  api-password: admin
  jwt-secret: local-development-secret-change-me
  postgres-password: postgress
  rabbitmq-user: guest
  rabbitmq-password: guest